"""Add time_to_complete_minutes to QuizPack

Revision ID: 5ff7c5e46a9b
Revises: 
Create Date: 2025-07-22 00:09:58.738601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ff7c5e46a9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_pack', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_to_complete_minutes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_pack', schema=None) as batch_op:
        batch_op.drop_column('time_to_complete_minutes')

    # ### end Alembic commands ###
